In [56]:
import psycopg2 
import pandas as pd
import numpy as np;
import matplotlib.pyplot as plt
import seaborn as sns

# Set display option to show all columns
pd.set_option('display.max_columns', None)

# Code to ignore warnings from function usage
import warnings;
warnings.filterwarnings('ignore')

import os

import networkx as nx

from decorator import decorator

from networkx.utils import create_random_state, create_py_random_state

from multiprocessing import Pool, cpu_count

import multiprocessing as mp

import time

from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
import plotly.graph_objs as go
import plotly
import plotly.express as px
init_notebook_mode(connected=True)

In [2]:
# Establish a connection to the PostgreSQL database
try:
    # Establish a connection to the PostgreSQL database
    connection = psycopg2.connect(
        host='localhost',
        database='leagueoflegendsapidata',
        user='postgres',
        password='naruto789',
        port=5432
    )
    print("Connected to the database")

    # Join the tables and retrieve data
    query = """
    SELECT pm.*, p.summoner_name, m.*
    FROM playerMatches AS pm
    JOIN player AS p ON pm.puuid = p.puuid
    JOIN matches AS m ON pm.match_id = m.match_id;
    """

    # Create a DataFrame from the query result
    dataframe = pd.read_sql_query(query, connection)

    # Close the database connection
    connection.close()
    print("Connection closed")

except psycopg2.Error as e:
    print("Error connecting to the database:", e)

Connected to the database
Connection closed

In [ ]:
df = dataframe.copy()

In [17]:
df.head()

,puuid,match_id,assists,baronkills,bountylevel,champexperience,champlevel,championid,championname,championtransform,consumablespurchased,damagedealttobuildings,damagedealttoobjectives,damagedealttoturrets,damageselfmitigated,deaths,detectorwardsplaced,doublekills,dragonkills,firstbloodassist,firstbloodkill,firsttowerassist,firsttowerkill,gameendedinearlysurrender,gameendedinsurrender,goldearned,goldspent,individualposition,inhibitorkills,inhibitortakedowns,inhibitorslost,item0,item1,item2,item3,item4,item5,item6,itemspurchased,killingsprees,kills,lane,largestcriticalstrike,largestkillingspree,largestmultikill,longesttimespentliving,magicdamagedealt,magicdamagedealttochampions,magicdamagetaken,neutralminionskilled,nexuskills,nexustakedowns,nexuslost,objectivesstolen,objectivesstolenassists,participantid,pentakills,physicaldamagedealt,physicaldamagedealttochampions,physicaldamagetaken,profileicon,quadrakills,riotidname,riotidtagline,champion_role,sightwardsboughtingame,spell1casts,spell2casts,spell3casts,spell4casts,summoner1casts,summoner1id,summoner2casts,summoner2id,summonerid,summonerlevel,summonername,teamearlysurrendered,teamid,teamposition,timeccingothers,timeplayed,totaldamagedealt,totaldamagedealttochampions,totaldamageshieldedonteammates,totaldamagetaken,totalheal,totalhealsonteammates,totalminionskilled,totaltimeccdealt,totaltimespentdead,totalunitshealed,triplekills,truedamagedealt,truedamagedealttochampions,truedamagetaken,turretkills,turrettakedowns,turretslost,unrealkills,visionscore,visionwardsboughtingame,wardskilled,wardsplaced,win,summoner_name,match_id,dataversion,participants,game_creation,game_duration,game_end_time_stamp,game_id,game_mode,game_name,game_start_time_stamp,game_type,game_version,map_id,platform_id,queue_id,winning_team_id,losing_team_id
0,Gy6gRr7cod5HZFEe9q_pxEXp7rzIHgS7uZsiVS6jQ_eeNq...,NA1_4763140725,16,0,0,17546,17,63,Brand,False,0,0,0,0,12366,10,0,1,0,False,False,False,False,False,False,12058,11600,Invalid,0,0,1,6653,3020,3116,3102,4630,1026,2052,13,3,9,NONE,0,2,2,227,53887,32716,20984,0,0,0,1,0,0,6,0,2199,223,2385,5252,0,,,SUPPORT,0,48,63,37,11,5,14,2,4,VOjngyS4m_NW7_2MsiYSNx-FXygy1T4rDBa4JsLGJldU3VQT,403,lmEIsa,False,200,,43,1094,56800,33653,0,23530,2436,0,27,278,246,1,0,714,714,160,0,0,4,0,0,0,0,0,False,lmEIsa,NA1_4763140725,2,[jVJnRLTxshkysZBPagvrS7ezwVczgyV_1f_3kIKuYTsKu...,1693719927066,1094,2023-09-02 23:03:51.151000,4763140725,ARAM,teambuilder-match-4763140725,2023-09-02 22:45:36.616000,MATCHED_GAME,13.17.529.525,12,NA1,450,100,200
1,t0SMnWYXZz05IEd6r98Y9ixLj2yeQnXg-ESzNKd-YUjIIb...,NA1_4749987091,20,0,0,21270,18,888,Renata,False,0,468,468,468,22130,7,0,0,0,False,False,True,False,False,False,13391,11700,Invalid,0,1,1,3040,6653,4637,1058,1058,0,2052,12,0,2,MIDDLE,0,0,1,445,33719,6584,13159,0,0,0,1,0,0,6,0,3334,232,7681,3156,0,,,SUPPORT,0,57,8,43,9,5,21,5,4,M1dNTNNlFT8jo-9CZ3DdKeDrBcI95d7Bn7takZZfRczKppM,217,manshowjugy,False,200,,24,1466,40760,10523,1270,25608,730,94,24,266,184,5,0,3706,3706,4767,0,2,4,0,0,0,0,0,False,manshowjugy,NA1_4749987091,2,[otgzAB6MpiaJdC8I4v9WQoMNg5UYgMJ5ill-gqjDC615q...,1692407004484,1466,2023-08-18 18:28:29.754000,4749987091,ARAM,teambuilder-match-4749987091,2023-08-18 18:04:03.263000,MATCHED_GAME,13.16.525.6443,12,NA1,450,100,200
2,3V6JHOb7TsWG8vF_qoNNY3Fg3AwpV2pMRdf7kfc_nbGjc7...,NA1_4743564593,15,0,0,16005,16,81,Ezreal,False,1,0,0,0,8737,9,0,1,0,False,False,False,False,False,False,11790,9950,Invalid,0,0,1,3177,3042,6675,3158,3133,1018,2052,14,2,7,NONE,582,3,2,350,9143,5947,18444,0,0,0,1,0,0,1,0,25861,8147,2825,1391,0,,,SUPPORT,0,68,44,11,8,4,6,3,4,mTep_4o6d5Qdlv3E26gC5MumQUBUqIFzVCMFPmEg8IduzcY,120,Skyreaxh,False,100,,0,1163,35223,14312,0,21527,1625,0,33,0,242,1,0,217,217,257,0,0,4,0,0,0,0,0,False,Skyreaxh,NA1_4743564593,2,[3V6JHOb7TsWG8vF_qoNNY3Fg3AwpV2pMRdf7kfc_nbGjc...,1691808021126,1163,2023-08-11 20:00:17.739000,4743564593,ARAM,teambuilder-match-4743564593,2023-08-11 19:40:54.595000,MATCHED_GAME,13.15.524.1760,12,NA1,450,200,100
3,Yg2aN2rK3xLy_ahYuYqiZY-mG0d-_MlnDcdWZlk03gmqnl...,NA1_4743564593,19,0,0,17392,17,235,Senna,False,2,646,646,646,11259,11,0,2,0,False,False,False,False,False,False,15659,14850,Invalid,0,0,1,6672,3009,3124,3004,3153,3035,2052,21,5,14,NONE,227,4,4,285,6753,3159,20199,0,0,0,1,0,0,2,0,55889,20855,5989,5091,1,,,SUPPORT,0,46,33,16,6,5,6,4,4,Q57hNWxlJHvSh4HGKHZxojWYlcgWLP-pwt35RKeTPMvaQQE,263,MikleM,False,100,,33,1163,63324,24673,1608,26428,7354,1616,47,178,332,5,1,681,658,239,0,0,4,0,0,0,0,0,False,MikleM,NA1_4743564593,2,[3V6JHOb7TsWG8vF_qoNNY3Fg3AwpV2pMRdf7kfc_nbGjc...,1691808021126,1163,2023-08-11 20:00:17.739000,4743564593,ARAM,teambuilder-match-4743564593,2023-08-11 19:40:54.595000,MATCHED_GAME,13.15.524.1760,12,NA1,450,200,100
4,piIZXy9v-1FJqmWpmz4J1QTzczFPQkEwWfyUs8tTzdiY26...,NA1_4743564593,13,0,0,17325,17,145,Kaisa,False,0,2205,2205,2205,15447,9,0,0,0,False,True,False,False,False,False,13562,12550,Invalid,1,1,0,3115,3042,3124,3006,6670,2015,2052,24,4,9,NONE,0,2,1,145,30577,18517,8487,0,1,1,0,0,0,6,0,24858,7904,12457,4414,0,,,DUO,0,31,67,31,6,5,4,6,7,FRP2bI6RL_bzmq7NP5Q5K7OXDjKttptlpUFM2e_dlak4twkp,312,DankestKnightt,False,200,,0,1163,55435,26422,0,21460,4123,398,64,0,220,3,0,0,0,514,1,3,1,0,0,0,0,0,True,dankestknightt,NA1_4743564593,2,[3V6JHOb7TsWG8vF_qoNNY3Fg3AwpV2pMRdf7kfc_nbGjc...,1691808021126,1163,2023-08-11 20:00:17.739000,4743564593,ARAM,teambuilder-match-4743564593,2023-08-11 19:40:54.595000,MATCHED_GAME,13.15.524.1760,12,NA1,450,200,100

In [18]:
# Convert game duration to minutes
df['game_duration_minutes'] = df['game_duration'] / 60

In [19]:
# Drop the original 'participants' column
df.drop(columns=['game_duration'], inplace=True)

In [20]:
# Convert the 'participants' column to a DataFrame
participants_df = df['participants'].apply(pd.Series)

# Concatenate the new participant columns to the original DataFrame
df = pd.concat([df, participants_df], axis=1)

# Drop the original 'participants' column
df.drop(columns=['participants'], inplace=True)

In [21]:
# Standardize the summonerName column to lowercase
df['summoner_name'] = df['summoner_name'].str.lower()

In [22]:
# Remove duplicate columns pandas DataFrame
df = df.loc[:,~df.columns.duplicated()]

In [58]:
# Take a random sample of data_scaled
sample_df = df.sample(n=100, random_state=42)

In [28]:
def create_summoner_network(df):
    # Assuming your original DataFrame is named 'df' and contains a 'summoner_name' column

    # Create an empty DataFrame to store the network data
    network_df = pd.DataFrame(columns=['player1', 'player2', 'games_played_together'])

    # Create a set to store unique summoner names
    unique_summoners = set(df['summoner_name'])

    # Get the total number of unique summoners
    total_summoners = len(unique_summoners)

    # Counter to track the progress
    progress_counter = 0

    # Iterate through unique summoner names
    for player1 in unique_summoners:
        for player2 in unique_summoners:
            if player1 != player2:
                # Filter rows where both players are present in the same game
                common_games = df[(df['summoner_name'] == player1) | (df['summoner_name'] == player2)]['match_id'].nunique()
                if common_games > 0:
                    # Check if the current row is already in the network DataFrame
                    if not ((network_df['player1'] == player1) & (network_df['player2'] == player2)).any():
                        # check if the inverse of the row is already in the network DataFrame
                        if not ((network_df['player1'] == player2) & (network_df['player2'] == player1)).any():
                            network_df = network_df.append({'player1': player1, 'player2': player2, 'games_played_together': common_games}, ignore_index=True)

        # Update the progress every 100 iterations
        progress_counter += 1
        if progress_counter % 10 == 0:
            print(f'Progress: {progress_counter}/{total_summoners}', flush=True)  # Use flush=True

    # Optional: Sort the network DataFrame by the number of games played together
    network_df = network_df.sort_values(by='games_played_together', ascending=False)

    # Return the resulting network DataFrame
    return network_df

In [59]:
summoner_network_df = create_summoner_network(sample_df)

Progress: 10/100
Progress: 20/100
Progress: 30/100
Progress: 40/100
Progress: 50/100
Progress: 60/100
Progress: 70/100
Progress: 80/100
Progress: 90/100
Progress: 100/100

In [60]:
summoner_network_df.head()

        player1    player2 games_played_together
0     miniman13  c4ctusg0d                     2
3298   còcacòla  eniighten                     2
3305   còcacòla   ionst0rm                     2
3304   còcacòla    wöntuan                     2
3303   còcacòla  wolielill                     2

In [67]:
common_games = df[(df['summoner_name'] == 'miniman13') | (df['summoner_name'] == 'c4ctusg0d')]['match_id'].nunique()
print(common_games)

6

In [61]:
summoner_network_df['games_played_together'] = summoner_network_df['games_played_together'].astype(int)

In [62]:
# nx.from_pandas_edgelist returns a graph from a Pandas DataFrame containing an edge list
G = nx.from_pandas_edgelist(summoner_network_df, 'player1', "player2", edge_attr = "games_played_together", create_using = nx.Graph())

In [53]:
G

In [ ]:
# The number of unique connections
# Creating functions to calculate the number of unique connections per character, Degree Centrality, Eigenvector Centrality, and Betweenness Centrality
def numUniqueConnec(G):
    numUniqueConnection = list(G.degree())
    
    numUniqueConnection = sorted(numUniqueConnection, key = lambda x:x[1], reverse = True)
    
    numUniqueConnection = pd.DataFrame.from_dict(numUniqueConnection)
    
    numUniqueConnection.columns = (["player", "NumberOfUniqueHCPConnections"])
    
    return numUniqueConnection

In [63]:
numUniqueConnec(G)

           Character  NumberOfUniqueHCPConnections
0          miniman13                            99
1          c4ctusg0d                            99
2           còcacòla                            99
3          eniighten                            99
4           ionst0rm                            99
..               ...                           ...
95         mrnyancat                            99
96         wyvern192                            99
97             blänk                            99
98  africancolonizer                            99
99      this is gogi                            99

[100 rows x 2 columns]

In [54]:
def draw_plotly_network_graph(Graph_obj, filter = None, filter_nodesbydegree = None):
    G_dup = Graph_obj.copy()

    degrees = nx.classes.degree(G_dup)
    
    degree_df = pd.DataFrame(degrees)
    
    # Filter out the nodes with fewer connections
    if filter is not None:
        top = deg_centrality_sort[:filter_nodesbydegree]["Character"].values# sort the top characters using filter_nodesbydegree
        
        G_dup.remove_nodes_from([node
                             for node in G_dup.nodes
                             if node not in top
                            ]) 

    pos = nx.spring_layout(G_dup)

    for n, p in pos.items():
        G_dup.nodes[n]['pos'] = p

    # Create edges 
    # Add edges as disconnected lines in a single trace and nodes as a scatter trace
    edge_trace = go.Scatter(
        x = [],
        y = [],
        line = dict(width = 0.5, color = '#888'),
        hoverinfo = 'none',
        mode = 'lines')

    for edge in G_dup.edges():
        x0, y0 = G_dup.nodes[edge[0]]['pos']
        
        x1, y1 = G_dup.nodes[edge[1]]['pos']
        
        edge_trace['x'] += tuple([x0, x1, None])
        
        edge_trace['y'] += tuple([y0, y1, None])

    node_trace = go.Scatter(
        x = [],
        y = [],
        text = [],
        mode = 'markers',
        hoverinfo = 'text',
        marker = dict(
            showscale = True,
            colorscale = 'RdBu',
            reversescale = True,
            color = [],
            size = 15,
            colorbar = dict(
                thickness = 10,
                title = 'Node Connections',
                xanchor = 'left',
                titleside = 'right'
            ),
            line = dict(width = 0)))

    for node in G_dup.nodes():
        x, y = G_dup.nodes[node]['pos']
        
        node_trace['x'] += tuple([x])
        
        node_trace['y'] += tuple([y])

    # Color node points by the number of connections
    for node, adjacencies in enumerate(G_dup.adjacency()):
        node_trace['marker']['color'] += tuple([int(degree_df[degree_df[0] == adjacencies[0]][1].values)])
        
        node_info = adjacencies[0] + '<br /># of connections: ' + str(int(degree_df[degree_df[0] == adjacencies[0]][1].values))
        
        node_trace['text'] += tuple([node_info])

    # Create a network graph
    fig = go.Figure(data = [edge_trace, node_trace],
                 layout = go.Layout(
                    title = '<br>Summoner_name network connections',
                    titlefont = dict(size = 20),
                    showlegend = False,
                    hovermode = 'closest',
                    margin = dict(b = 20, l = 5, r = 5, t = 0),
                    annotations=[ dict(
                        text = "",
                        showarrow = False,
                        xref = "paper", yref = "paper") ],
                    xaxis = dict(showgrid = False, zeroline = False, showticklabels = False),
                    yaxis = dict(showgrid = False, zeroline = False, showticklabels = False)))

    iplot(fig)

In [57]:
draw_plotly_network_graph(Graph_obj = G, filter = None, filter_nodesbydegree = None)
# 2 minutes for 100 player from orginal database